var sampleHouses= [
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8957927",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"900 Pennsylvania St #600",
    "City":"Denver",
    "Zip":80203,
    "Price Type":"List Price",
    "List/Sold $":"$2,700,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":3023,
    "SqFt Above":"3,023",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2721353",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"900 N Pennsylvania St #100",
    "City":"Denver",
    "Zip":80203,
    "Price Type":"List Price",
    "List/Sold $":"$2,295,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2613,
    "SqFt Above":"2,613",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"4327588",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"707 Washington St #424",
    "City":"Denver",
    "Zip":80203,
    "Price Type":"List Price",
    "List/Sold $":"$1,595,000",
    "Beds":3,
    "Baths":6,
    "Ttl Sqft":6064,
    "SqFt Above":"4,140",
    "Listing Office":"LIV Sotheby's International Realty"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3260035",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"2000 Little Raven St #4B",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$1,375,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":2196,
    "SqFt Above":"2,196",
    "Listing Office":"THE RESOURCE GROUP LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9170044",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1720 Wynkoop St #212",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$1,300,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":2456,
    "SqFt Above":"2,456",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2605219",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"975 Lincoln St #15B",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$1,300,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":3865,
    "SqFt Above":"3,865",
    "Listing Office":"Colorado and Company Real Estate, Inc"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2695644",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1737 Central St #5",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$1,275,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2000,
    "SqFt Above":"2,000",
    "Listing Office":"Denver Fine Properties LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"1891847",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3535 Tejon St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$1,199,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":4399,
    "SqFt Above":"3,322",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2349809",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1737 Central St #4",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$1,175,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2000,
    "SqFt Above":"2,000",
    "Listing Office":"Denver Fine Properties LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9906053",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1891 Curtis St #1807",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$1,100,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":2430,
    "SqFt Above":"2,430",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"1878320",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"2011 Osceola St",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$1,100,000",
    "Beds":4,
    "Baths":3,
    "Ttl Sqft":3296,
    "SqFt Above":"3,296",
    "Listing Office":"Brixton Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"1806160",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1737 Central St #3",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$1,075,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2000,
    "SqFt Above":"2,000",
    "Listing Office":"Denver Fine Properties LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"4680207",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"2435 Hooker St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$995,000",
    "Beds":6,
    "Baths":4,
    "Ttl Sqft":3643,
    "SqFt Above":"2,263",
    "Listing Office":"Madison & Company Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9331035",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"891 14th St #910",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$925,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1307,
    "SqFt Above":"1,307",
    "Listing Office":"SLIFER SMITH & FRAMPTON DENV"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2164247",
    "Sts":"A",
    "Style":"3+ Story",
    "Address":"4422 Winona Ct",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$915,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":3404,
    "SqFt Above":"3,404",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"6279034",
    "Sts":"A",
    "Style":"3+ Story",
    "Address":"3537 W 40th Ave",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$899,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":3529,
    "SqFt Above":"2,424",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7837483",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"6595 W 46th Pl",
    "City":"Wheat Ridge",
    "Zip":80033,
    "Price Type":"List Price",
    "List/Sold $":"$895,000",
    "Beds":4,
    "Baths":5,
    "Ttl Sqft":6053,
    "SqFt Above":"3,898",
    "Listing Office":"YOUR CASTLE SERVICES"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"6653000",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1401 Delgany St #204",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$870,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":1965,
    "SqFt Above":"1,965",
    "Listing Office":"SLIFER SMITH & FRAMPTON DENV"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5453612",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"1732 W 34th St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$859,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2566,
    "SqFt Above":"2,566",
    "Listing Office":"RE/MAX PROFESSIONALS"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8220585",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3612 Wyandot St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$850,000",
    "Beds":4,
    "Baths":5,
    "Ttl Sqft":3122,
    "SqFt Above":"2,219",
    "Listing Office":"Modlux Realty"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"I766708",
    "Sts":"A",
    "Style":"Other Multi-unit",
    "Address":"1912 N Logan St",
    "City":"Denver",
    "Zip":80203,
    "Price Type":"",
    "List/Sold $":"$850,000",
    "Beds":4,
    "Baths":4,
    "Ttl Sqft":3857,
    "SqFt Above":"2,598",
    "Listing Office":"Cherry Creek Properties LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5504702",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"1420 24th St #13",
    "City":"Denver",
    "Zip":80205,
    "Price Type":"List Price",
    "List/Sold $":"$849,500",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":2096,
    "SqFt Above":"2,096",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"1782734",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1401 Wewatta St #308",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$799,900",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1604,
    "SqFt Above":"1,604",
    "Listing Office":"CASTLES AND CONDOS REALTY"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7651349",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"1661 Yates St",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$750,000",
    "Beds":6,
    "Baths":4,
    "Ttl Sqft":4257,
    "SqFt Above":"2,671",
    "Listing Office":"THE KENTWOOD COMPANY"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"1894481",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"2728 Decatur St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$750,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":3236,
    "SqFt Above":"2,801",
    "Listing Office":"Proform, Inc"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3378932",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1863 Wazee St #1G",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$750,000",
    "Beds":1,
    "Baths":2,
    "Ttl Sqft":3563,
    "SqFt Above":"2,549",
    "Listing Office":"DUBROVA AND ASSOCIATES LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9069438",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"4555 Stuart St",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$709,900",
    "Beds":4,
    "Baths":4,
    "Ttl Sqft":2485,
    "SqFt Above":"2,485",
    "Listing Office":"MB BILLY HALAX REAL ESTATE"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9906421",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3835 Utica St",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$695,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":2347,
    "SqFt Above":"2,347",
    "Listing Office":"Dixon Realty"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"6397590",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1700 Bassett St #1401",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$692,900",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1220,
    "SqFt Above":"1,220",
    "Listing Office":"RE/MAX Cherry Creek"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7900439",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"3127 Newton St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$689,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":2074,
    "SqFt Above":"1,875",
    "Listing Office":"YOUR CASTLE MOUNTAIN PROPERTIES"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"1912725",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3333 W 20th Ave",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$685,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":2298,
    "SqFt Above":"2,298",
    "Listing Office":"RE/MAX Uptown Inc"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"6825448",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"2028 W 33rd Ave #1",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$679,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":1740,
    "SqFt Above":"1,740",
    "Listing Office":"RE/Max of Boulder"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"I781988",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"2028 W 33rd Ave #1",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"",
    "List/Sold $":"$679,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":1740,
    "SqFt Above":"1,740",
    "Listing Office":"RE/MAX of Boulder, Inc"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"6334747",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3536 Navajo St #106",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$675,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1915,
    "SqFt Above":"1,915",
    "Listing Office":"PRISTINE HOMES OF COLORADO LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"6306921",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3536 Navajo St #101",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$675,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1958,
    "SqFt Above":"1,958",
    "Listing Office":"PRISTINE HOMES OF COLORADO LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2385455",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"2057 Meade St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$674,900",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":2434,
    "SqFt Above":"2,434",
    "Listing Office":"PERRY & CO CHERRY CREEK NORTH"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2115161",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"3100 Stuart St",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$667,800",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":1864,
    "SqFt Above":"1,764",
    "Listing Office":"Your Castle Real Estate Inc"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3852129",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"4400 Winona Ct",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$650,000",
    "Beds":4,
    "Baths":3,
    "Ttl Sqft":3251,
    "SqFt Above":"2,576",
    "Listing Office":"RE/MAX AVENUES"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9104514",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"4696 Grove St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$650,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2572,
    "SqFt Above":"1,286",
    "Listing Office":"360DWELLINGS REAL ESTATE"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8495958",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"930 Acoma St #306",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$650,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1863,
    "SqFt Above":"1,863",
    "Listing Office":"Realty One Group Premier"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2153431",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"5158 W 33rd Ave",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$649,999",
    "Beds":4,
    "Baths":3,
    "Ttl Sqft":3810,
    "SqFt Above":"2,460",
    "Listing Office":"Keller Williams Preferred Realty"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"4895015",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"3344 Navajo St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$644,997",
    "Beds":3,
    "Baths":2,
    "Ttl Sqft":1560,
    "SqFt Above":"1,560",
    "Listing Office":"MB REAL ESTATE PROFESSIONA1S"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3241906",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3536 Navajo St #102",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$639,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1935,
    "SqFt Above":"1,935",
    "Listing Office":"PRISTINE HOMES OF COLORADO LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2265584",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3536 Navajo St #103",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$639,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1935,
    "SqFt Above":"1,935",
    "Listing Office":"PRISTINE HOMES OF COLORADO LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7634631",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3536 Navajo St #104",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$639,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1935,
    "SqFt Above":"1,935",
    "Listing Office":"PRISTINE HOMES OF COLORADO LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9449490",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3536 Navajo St #105",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$639,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1935,
    "SqFt Above":"1,935",
    "Listing Office":"PRISTINE HOMES OF COLORADO LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3370907",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"2001 Lincoln St #1522",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$630,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1468,
    "SqFt Above":"1,468",
    "Listing Office":"RE/MAX ALLIANCE"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"I782376",
    "Sts":"A",
    "Style":"Other Multi-unit",
    "Address":"2001 Lincoln St #1522",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"",
    "List/Sold $":"$630,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1468,
    "SqFt Above":"1,468",
    "Listing Office":"RE/MAX Alliance-Longmont"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9081694",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"3839 Meade St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$629,950",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2214,
    "SqFt Above":"1,107",
    "Listing Office":"MB SOUTHWEST SABINA & COMPANY"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7836208",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1140 Cherokee St #401",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$599,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1785,
    "SqFt Above":"1,785",
    "Listing Office":"MODGLIN REAL ESTATE GROUP"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"4072281",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"2438 Ames St",
    "City":"Edgewater",
    "Zip":80214,
    "Price Type":"List Price",
    "List/Sold $":"$599,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":2035,
    "SqFt Above":"2,035",
    "Listing Office":"8Z Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8100620",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"2436 Ames St",
    "City":"Edgewater",
    "Zip":80214,
    "Price Type":"List Price",
    "List/Sold $":"$599,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":2035,
    "SqFt Above":"2,035",
    "Listing Office":"8Z Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8365432",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3323 W 17th Ave #106",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$585,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":1831,
    "SqFt Above":"1,831",
    "Listing Office":"MB SOUTHWEST SABINA & COMPANY"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2136062",
    "Sts":"A",
    "Style":"3+ Story",
    "Address":"4015 Fenton Ct",
    "City":"Wheat Ridge",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$579,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2914,
    "SqFt Above":"1,899",
    "Listing Office":"Greenspot Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8730744",
    "Sts":"A",
    "Style":"3+ Story",
    "Address":"4025 Fenton Ct",
    "City":"Wheat Ridge",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$579,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2914,
    "SqFt Above":"2,134",
    "Listing Office":"Greenspot Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3263733",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"891 14th St #3506",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$575,000",
    "Beds":1,
    "Baths":1,
    "Ttl Sqft":900,
    "SqFt Above":"900",
    "Listing Office":"Kentwood Co at Cherry Creek"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5069599",
    "Sts":"A",
    "Style":"Raised Ranch",
    "Address":"7750 W 9th Ave",
    "City":"Lakewood",
    "Zip":80214,
    "Price Type":"List Price",
    "List/Sold $":"$575,000",
    "Beds":4,
    "Baths":3,
    "Ttl Sqft":3314,
    "SqFt Above":"1,657",
    "Listing Office":"ALARIS PROPERTIES LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3690194",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"975 N Lincoln St #8C-N",
    "City":"Denver",
    "Zip":80203,
    "Price Type":"List Price",
    "List/Sold $":"$575,000",
    "Beds":3,
    "Baths":2,
    "Ttl Sqft":1835,
    "SqFt Above":"1,835",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5800530",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3323 W 17th Ave #105",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$570,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":1831,
    "SqFt Above":"1,831",
    "Listing Office":"MB SOUTHWEST SABINA & COMPANY"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7331536",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3323 W 17th Ave #102",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$570,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":1831,
    "SqFt Above":"1,831",
    "Listing Office":"MB SOUTHWEST SABINA & COMPANY"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5347893",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1777 Larimer St #908",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$569,500",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1909,
    "SqFt Above":"1,909",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"6796274",
    "Sts":"A",
    "Style":"Other Multi-unit",
    "Address":"1740 Lowell Blvd",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$569,500",
    "Beds":3,
    "Baths":2,
    "Ttl Sqft":1744,
    "SqFt Above":"1,142",
    "Listing Office":"RE/MAX CENTRAL ALLIANCE"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2851996",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"975 N Lincoln St #7B-N",
    "City":"Denver",
    "Zip":80203,
    "Price Type":"List Price",
    "List/Sold $":"$550,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2272,
    "SqFt Above":"2,272",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3615805",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"2984 Hooker St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$550,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1697,
    "SqFt Above":"1,438",
    "Listing Office":"TRELORA"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3411948",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"2345 Walnut St #26",
    "City":"Denver",
    "Zip":80205,
    "Price Type":"List Price",
    "List/Sold $":"$549,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1425,
    "SqFt Above":"1,425",
    "Listing Office":"RE/Max of Boulder"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"I782484",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"2345 Walnut St #26",
    "City":"Denver",
    "Zip":80205,
    "Price Type":"",
    "List/Sold $":"$549,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1425,
    "SqFt Above":"1,425",
    "Listing Office":"RE/MAX of Boulder, Inc"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"4045540",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"4570 Hooker St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$542,500",
    "Beds":3,
    "Baths":2,
    "Ttl Sqft":2491,
    "SqFt Above":"983",
    "Listing Office":"RE/MAX NORTHWEST INC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8390472",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"475 W 12th Ave #7G",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$540,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1409,
    "SqFt Above":"1,409",
    "Listing Office":"Porchlight Real Estate Group"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2231629",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"2900 Inca St #22",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$539,900",
    "Beds":2,
    "Baths":4,
    "Ttl Sqft":1452,
    "SqFt Above":"1,423",
    "Listing Office":"DUBROVA AND ASSOCIATES LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8929883",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"2506 W Caithness Pl",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$534,900",
    "Beds":5,
    "Baths":2,
    "Ttl Sqft":2170,
    "SqFt Above":"1,606",
    "Listing Office":"Vision Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3781548",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"3031 W 27th Ave",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$530,000",
    "Beds":4,
    "Baths":2,
    "Ttl Sqft":1868,
    "SqFt Above":"1,072",
    "Listing Office":"Kentwood Co at Cherry Creek"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9087731",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"4443 Vallejo St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$529,900",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1570,
    "SqFt Above":"1,376",
    "Listing Office":"Colorado Flat Fee Realty Inc"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8672983",
    "Sts":"A",
    "Style":"Other Multi-unit",
    "Address":"4283 Hooker St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$525,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1886,
    "SqFt Above":"943",
    "Listing Office":"Lori Corken & Company"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2616409",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"3186 W 35th Ave",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$525,000",
    "Beds":3,
    "Baths":2,
    "Ttl Sqft":1921,
    "SqFt Above":"1,061",
    "Listing Office":"RE/MAX CENTRAL ALLIANCE"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"1550149",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"4844 Stuart St",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$525,000",
    "Beds":3,
    "Baths":2,
    "Ttl Sqft":2034,
    "SqFt Above":"1,017",
    "Listing Office":"Workman & Associates"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"6418994",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1551 Larimer St #1705",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$510,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1205,
    "SqFt Above":"1,205",
    "Listing Office":"Century 21 Trenka Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5805411",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"891 14th St #3606",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$500,000",
    "Beds":1,
    "Baths":1,
    "Ttl Sqft":900,
    "SqFt Above":"900",
    "Listing Office":"SLIFER SMITH & FRAMPTON DENV"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5566052",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"3331 Yukon Ct",
    "City":"Wheat Ridge",
    "Zip":80033,
    "Price Type":"List Price",
    "List/Sold $":"$499,900",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2662,
    "SqFt Above":"1,816",
    "Listing Office":"BROKERS GUILD-CHERRY CREEK LTD"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3821990",
    "Sts":"A",
    "Style":"Other Multi-unit",
    "Address":"5790 W 39 Pl",
    "City":"Wheat Ridge",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$499,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2514,
    "SqFt Above":"1,784",
    "Listing Office":"Greenspot Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"1800950",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"3690 Yukon Ct",
    "City":"Wheat Ridge",
    "Zip":80033,
    "Price Type":"Base Price",
    "List/Sold $":"$498,500",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2697,
    "SqFt Above":"1,851",
    "Listing Office":"BROKERS GUILD-CHERRY CREEK LTD"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"1875354",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3127 W Conejos Pl #2",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$495,000",
    "Beds":3,
    "Baths":4,
    "Ttl Sqft":2044,
    "SqFt Above":"2,044",
    "Listing Office":"YOUR CASTLE SERVICES"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5985233",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"6905 W 44th Ave",
    "City":"Wheat Ridge",
    "Zip":80033,
    "Price Type":"List Price",
    "List/Sold $":"$494,000",
    "Beds":5,
    "Baths":4,
    "Ttl Sqft":3500,
    "SqFt Above":"2,003",
    "Listing Office":"NOSTALGIC HOMES"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"4467462",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"975 N Lincoln St #5E-N",
    "City":"Denver",
    "Zip":80203,
    "Price Type":"List Price",
    "List/Sold $":"$485,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1284,
    "SqFt Above":"1,284",
    "Listing Office":"MB Alborz Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3166679",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"1453 27th St",
    "City":"Denver",
    "Zip":80205,
    "Price Type":"List Price",
    "List/Sold $":"$479,900",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1332,
    "SqFt Above":"1,332",
    "Listing Office":"Redfin Corporation"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8918289",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"5850 W 39th Pl",
    "City":"Wheat Ridge",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$479,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":1764,
    "SqFt Above":"1,764",
    "Listing Office":"Greenspot Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"6749836",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"5898 W 39th Pl",
    "City":"Wheat Ridge",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$479,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":1764,
    "SqFt Above":"1,764",
    "Listing Office":"Greenspot Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8686817",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"891 14th St #3314",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$475,000",
    "Beds":1,
    "Baths":1,
    "Ttl Sqft":893,
    "SqFt Above":"893",
    "Listing Office":"SLIFER SMITH & FRAMPTON DENV"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8163168",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"3265 Yukon Ct",
    "City":"Wheat Ridge",
    "Zip":80033,
    "Price Type":"Base Price",
    "List/Sold $":"$474,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":2330,
    "SqFt Above":"1,620",
    "Listing Office":"BROKERS GUILD-CHERRY CREEK LTD"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3324973",
    "Sts":"A",
    "Style":"Multi-Level",
    "Address":"4873 Quitman St",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$469,900",
    "Beds":4,
    "Baths":3,
    "Ttl Sqft":1945,
    "SqFt Above":"1,471",
    "Listing Office":"Keller Williams DTC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7683647",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"5880 W 39th Pl",
    "City":"Wheat Ridge",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$466,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":1764,
    "SqFt Above":"1,764",
    "Listing Office":"Greenspot Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2740641",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"5870 W 39th Pl",
    "City":"Wheat Ridge",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$459,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":1764,
    "SqFt Above":"1,764",
    "Listing Office":"Greenspot Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3279823",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"5890 W 39th Pl",
    "City":"Wheat Ridge",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$459,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":1764,
    "SqFt Above":"1,764",
    "Listing Office":"Greenspot Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5901113",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"2735 Grove St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$455,000",
    "Beds":0,
    "Baths":0,
    "Ttl Sqft":799,
    "SqFt Above":"799",
    "Listing Office":"Ion Real Estate LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2232921",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"3860 Osceola St",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$450,000",
    "Beds":4,
    "Baths":2,
    "Ttl Sqft":2092,
    "SqFt Above":"1,392",
    "Listing Office":"Keller Williams Advantage Realty LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"6575777",
    "Sts":"A",
    "Style":"Other Multi-unit",
    "Address":"2000 Marshall St",
    "City":"Edgewater",
    "Zip":80214,
    "Price Type":"List Price",
    "List/Sold $":"$450,000",
    "Beds":6,
    "Baths":4,
    "Ttl Sqft":4020,
    "SqFt Above":"2,010",
    "Listing Office":"Porchlight Real Estate Group"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"4797616",
    "Sts":"A",
    "Style":"Other Multi-unit",
    "Address":"2010 Marshall St",
    "City":"Edgewater",
    "Zip":80214,
    "Price Type":"List Price",
    "List/Sold $":"$450,000",
    "Beds":6,
    "Baths":4,
    "Ttl Sqft":4020,
    "SqFt Above":"2,010",
    "Listing Office":"Porchlight Real Estate Group"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3114896",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"3922 Alcott St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$449,900",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1357,
    "SqFt Above":"1,177",
    "Listing Office":"LIV Sotheby's International Realty"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"6648696",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3618 W 24th Ave #C",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$445,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1561,
    "SqFt Above":"1,561",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3442773",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"1015 Federal Blvd",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$435,000",
    "Beds":1,
    "Baths":2,
    "Ttl Sqft":1600,
    "SqFt Above":"1,600",
    "Listing Office":"Keller Williams Integrity Real Estate LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3813045",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"2630 River Dr",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$435,000",
    "Beds":2,
    "Baths":1,
    "Ttl Sqft":1120,
    "SqFt Above":"1,120",
    "Listing Office":"Porchlight Real Estate Group"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2227177",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"3119 W 18th Ave",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$435,000",
    "Beds":2,
    "Baths":4,
    "Ttl Sqft":1320,
    "SqFt Above":"1,320",
    "Listing Office":"LIV Sotheby's International Realty"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"4784287",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"2154 Gray St",
    "City":"Edgewater",
    "Zip":80214,
    "Price Type":"List Price",
    "List/Sold $":"$429,973",
    "Beds":4,
    "Baths":2,
    "Ttl Sqft":1890,
    "SqFt Above":"945",
    "Listing Office":"Hothem & Associates"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9097125",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1475 Delgany St #510",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$429,000",
    "Beds":2,
    "Baths":1,
    "Ttl Sqft":1034,
    "SqFt Above":"1,034",
    "Listing Office":"SLIFER SMITH & FRAMPTON DENV"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5797918",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"2001 Lincoln St #1920",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$425,000",
    "Beds":1,
    "Baths":2,
    "Ttl Sqft":818,
    "SqFt Above":"818",
    "Listing Office":"LIV Sotheby's International Realty"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"4866287",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"4160 Ingalls Ct",
    "City":"Wheat Ridge",
    "Zip":80033,
    "Price Type":"List Price",
    "List/Sold $":"$419,900",
    "Beds":4,
    "Baths":2,
    "Ttl Sqft":2536,
    "SqFt Above":"1,268",
    "Listing Office":"RE/MAX Unlimited Inc"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8333380",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"2955 Inca St #3M",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$399,000",
    "Beds":1,
    "Baths":1,
    "Ttl Sqft":1045,
    "SqFt Above":"1,045",
    "Listing Office":"Aspen Gold Realty"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3483662",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"2437 W 35th Ave",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$399,000",
    "Beds":1,
    "Baths":1,
    "Ttl Sqft":1240,
    "SqFt Above":"620",
    "Listing Office":"Kentwood City Properties"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"1855028",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"5101 Zuni St",
    "City":"Denver",
    "Zip":80221,
    "Price Type":"List Price",
    "List/Sold $":"$395,000",
    "Beds":4,
    "Baths":2,
    "Ttl Sqft":2002,
    "SqFt Above":"1,001",
    "Listing Office":"Homeward Bound Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3775209",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"4893 Knox Ct",
    "City":"Denver",
    "Zip":80221,
    "Price Type":"List Price",
    "List/Sold $":"$389,950",
    "Beds":4,
    "Baths":2,
    "Ttl Sqft":1555,
    "SqFt Above":"933",
    "Listing Office":"Paisano Realty, Inc."
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7616255",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"2001 Lincoln St #1612",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$380,000",
    "Beds":1,
    "Baths":2,
    "Ttl Sqft":783,
    "SqFt Above":"783",
    "Listing Office":"TRELORA"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7859194",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"2020 Arapahoe St #960",
    "City":"Denver",
    "Zip":80205,
    "Price Type":"List Price",
    "List/Sold $":"$374,900",
    "Beds":1,
    "Baths":2,
    "Ttl Sqft":1041,
    "SqFt Above":"1,041",
    "Listing Office":"COX REAL ESTATE GROUP"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8863393",
    "Sts":"A",
    "Style":"Raised Ranch",
    "Address":"4676 Sherman St",
    "City":"Denver",
    "Zip":80216,
    "Price Type":"List Price",
    "List/Sold $":"$369,900",
    "Beds":3,
    "Baths":2,
    "Ttl Sqft":1624,
    "SqFt Above":"1,624",
    "Listing Office":"A2Z Realty LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9547398",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"3489 W 48th Ave",
    "City":"Denver",
    "Zip":80221,
    "Price Type":"List Price",
    "List/Sold $":"$369,900",
    "Beds":3,
    "Baths":1,
    "Ttl Sqft":1175,
    "SqFt Above":"1,076",
    "Listing Office":"RE/MAX Professionals"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7219969",
    "Sts":"A",
    "Style":"Multi-Level",
    "Address":"7665 W 23rd Pl",
    "City":"Lakewood",
    "Zip":80214,
    "Price Type":"List Price",
    "List/Sold $":"$365,000",
    "Beds":4,
    "Baths":2,
    "Ttl Sqft":2522,
    "SqFt Above":"1,850",
    "Listing Office":"RE/MAX NORTHWEST INC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7160239",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"975 N Lincoln St #4I-N",
    "City":"Denver",
    "Zip":80203,
    "Price Type":"List Price",
    "List/Sold $":"$365,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1074,
    "SqFt Above":"1,074",
    "Listing Office":"MB Alborz Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5952329",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"1050 Hooker St",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$365,000",
    "Beds":4,
    "Baths":1,
    "Ttl Sqft":1661,
    "SqFt Above":"1,661",
    "Listing Office":"Your Castle Real Estate Inc"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2336328",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1975 Grant St #427",
    "City":"Denver",
    "Zip":80203,
    "Price Type":"List Price",
    "List/Sold $":"$360,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":902,
    "SqFt Above":"902",
    "Listing Office":"Colorado Home Realty"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5800108",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"669 Washington St #201",
    "City":"Denver",
    "Zip":80203,
    "Price Type":"List Price",
    "List/Sold $":"$359,995",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1041,
    "SqFt Above":"1,041",
    "Listing Office":"Vision Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8988007",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1555 Central St #205",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$347,000",
    "Beds":1,
    "Baths":1,
    "Ttl Sqft":888,
    "SqFt Above":"888",
    "Listing Office":"YOUR CASTLE MOUNTAIN PROPERTIES"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8307998",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1747 Washington St #B307",
    "City":"Denver",
    "Zip":80203,
    "Price Type":"List Price",
    "List/Sold $":"$335,000",
    "Beds":2,
    "Baths":2,
    "Ttl Sqft":1027,
    "SqFt Above":"1,027",
    "Listing Office":"RE/MAX Success"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3351039",
    "Sts":"A",
    "Style":"Other Multi-unit",
    "Address":"3943 W 23rd Ave",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$330,000",
    "Beds":2,
    "Baths":1,
    "Ttl Sqft":851,
    "SqFt Above":"851",
    "Listing Office":"Real Estate Denver Team"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9005317",
    "Sts":"A",
    "Style":"Other Multi-unit",
    "Address":"3941 W 23rd Ave",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$330,000",
    "Beds":2,
    "Baths":1,
    "Ttl Sqft":1171,
    "SqFt Above":"851",
    "Listing Office":"Real Estate Denver Team"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7342181",
    "Sts":"A",
    "Style":"Other Multi-unit",
    "Address":"4951 W 36th Ave",
    "City":"Denver",
    "Zip":80212,
    "Price Type":"List Price",
    "List/Sold $":"$325,000",
    "Beds":2,
    "Baths":1,
    "Ttl Sqft":858,
    "SqFt Above":"858",
    "Listing Office":"RE/MAX NORTHWEST INC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2682996",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"2137 Clay St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$325,000",
    "Beds":2,
    "Baths":1,
    "Ttl Sqft":1178,
    "SqFt Above":"879",
    "Listing Office":"Generator Real Estate, LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7896398",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"1760 W Burlington Pl",
    "City":"Denver",
    "Zip":80221,
    "Price Type":"List Price",
    "List/Sold $":"$324,900",
    "Beds":3,
    "Baths":1,
    "Ttl Sqft":886,
    "SqFt Above":"886",
    "Listing Office":"Keller Williams Realty Downtown"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"6147602",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"2201 Lamar St",
    "City":"Edgewater",
    "Zip":80214,
    "Price Type":"List Price",
    "List/Sold $":"$320,000",
    "Beds":3,
    "Baths":1,
    "Ttl Sqft":1267,
    "SqFt Above":"1,267",
    "Listing Office":"RE/MAX ALLIANCE"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3464813",
    "Sts":"A",
    "Style":"2 Story",
    "Address":"1750 W Dixie Pl",
    "City":"Denver",
    "Zip":80221,
    "Price Type":"List Price",
    "List/Sold $":"$319,500",
    "Beds":3,
    "Baths":2,
    "Ttl Sqft":1189,
    "SqFt Above":"1,189",
    "Listing Office":"8Z Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8488776",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"4730 Clay St",
    "City":"Denver",
    "Zip":80211,
    "Price Type":"List Price",
    "List/Sold $":"$304,900",
    "Beds":3,
    "Baths":1,
    "Ttl Sqft":975,
    "SqFt Above":"975",
    "Listing Office":"BROKERS GUILD-CHERRY CREEK LTD"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"4953419",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1401 Wewatta St #713",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$299,900",
    "Beds":0,
    "Baths":1,
    "Ttl Sqft":593,
    "SqFt Above":"593",
    "Listing Office":"CASTLES AND CONDOS REALTY"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5604492",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"1438 Lipan St",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$275,000",
    "Beds":3,
    "Baths":1,
    "Ttl Sqft":843,
    "SqFt Above":"843",
    "Listing Office":"MB Pezzuti & Associates"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"3314702",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"1777 W 52nd Ct",
    "City":"Denver",
    "Zip":80221,
    "Price Type":"List Price",
    "List/Sold $":"$275,000",
    "Beds":2,
    "Baths":3,
    "Ttl Sqft":1424,
    "SqFt Above":"1,424",
    "Listing Office":"Shin Real Estate and Investments, Inc."
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7048026",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"2411 Fenton St",
    "City":"Edgewater",
    "Zip":80214,
    "Price Type":"List Price",
    "List/Sold $":"$262,500",
    "Beds":2,
    "Baths":1,
    "Ttl Sqft":1308,
    "SqFt Above":"1,008",
    "Listing Office":"Denver Luxury Real Estate"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"7482151",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"1727 Lake Shore Pl",
    "City":"Edgewater",
    "Zip":80214,
    "Price Type":"List Price",
    "List/Sold $":"$259,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":1248,
    "SqFt Above":"1,248",
    "Listing Office":"LT REAL ESTATE LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9608997",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1020 15th St #40K",
    "City":"Denver",
    "Zip":80202,
    "Price Type":"List Price",
    "List/Sold $":"$247,650",
    "Beds":1,
    "Baths":1,
    "Ttl Sqft":640,
    "SqFt Above":"640",
    "Listing Office":"HOME SAVINGS REALTY"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"8884312",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"1635 Yukon St",
    "City":"Lakewood",
    "Zip":80214,
    "Price Type":"List Price",
    "List/Sold $":"$245,000",
    "Beds":2,
    "Baths":1,
    "Ttl Sqft":1082,
    "SqFt Above":"1,082",
    "Listing Office":"Keller Williams Realty Downtown"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"2509018",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"5275 Ingalls St",
    "City":"Arvada",
    "Zip":80002,
    "Price Type":"List Price",
    "List/Sold $":"$239,900",
    "Beds":2,
    "Baths":1,
    "Ttl Sqft":720,
    "SqFt Above":"720",
    "Listing Office":"RE/MAX Masters Millennium"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9806937",
    "Sts":"A",
    "Style":"Townhouse",
    "Address":"1702 Depew St",
    "City":"Edgewater",
    "Zip":80214,
    "Price Type":"List Price",
    "List/Sold $":"$239,000",
    "Beds":3,
    "Baths":3,
    "Ttl Sqft":1248,
    "SqFt Above":"1,248",
    "Listing Office":"Porchlight Real Estate Group"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"4088044",
    "Sts":"A",
    "Style":"Condominium",
    "Address":"1419 Lipan St #3",
    "City":"Denver",
    "Zip":80204,
    "Price Type":"List Price",
    "List/Sold $":"$165,000",
    "Beds":1,
    "Baths":1,
    "Ttl Sqft":435,
    "SqFt Above":"435",
    "Listing Office":"Keller Williams Real Estate LLC"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5620027",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"4306 Sherman St",
    "City":"Denver",
    "Zip":80216,
    "Price Type":"List Price",
    "List/Sold $":"$150,000",
    "Beds":3,
    "Baths":1,
    "Ttl Sqft":970,
    "SqFt Above":"970",
    "Listing Office":"Keller Williams Realty Downtown"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"5611909",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"4310 Sherman St",
    "City":"Denver",
    "Zip":80216,
    "Price Type":"List Price",
    "List/Sold $":"$150,000",
    "Beds":0,
    "Baths":0,
    "Ttl Sqft":1,
    "SqFt Above":"0",
    "Listing Office":"Keller Williams Realty Downtown"
  },
  {
    "FIELD1":"",
    "FIELD2":"",
    "MLS #":"9765611",
    "Sts":"A",
    "Style":"Ranch/1 Story",
    "Address":"4314 Sherman St",
    "City":"Denver",
    "Zip":80216,
    "Price Type":"List Price",
    "List/Sold $":"$150,000",
    "Beds":2,
    "Baths":1,
    "Ttl Sqft":726,
    "SqFt Above":"726",
    "Listing Office":"Keller Williams Realty Downtown"
  }
];